### ISSUE TITLE
How to pause on android?

### ISSUE THREAD

**Issue by mariusbolik** [gokadzev/capacitor-music-controls-plugin-new#3]
How can I pause the player controls? It says that `updateElapsed()` and `updatePlaying()` are not implemented on android. Also the controls are not destroyed if the user ends the app.

**Comment by mariusbolik** [comment]
I'm not an expert, but it seems like capacitor android plugins can override the handleOnDestroy method to do any needed cleanup work. This could fix the issue with the music controls that won't hide after app is terminated.
Example: https://github.com/ionic-team/capacitor-plugins/search?q=handleOnDestroy

**Comment by gokadzev** [comment]
Notification problem should be fixed now, i will look at pause problem too.

**Comment by gokadzev** [comment]
Fixed, thanks!
