### ISSUE TITLE
error: cannot find symbol PendingIntent.FLAG_MUTABLE

### ISSUE THREAD

**Issue by mtrnik** [gokadzev/capacitor-music-controls-plugin-new#7]
Hello I am getting following error:

..../app/node_modules/capacitor-music-controls-plugin-new/android/src/main/java/com/gokadzev/capacitormusiccontrols/MusicControlsNotification.java:256: error: cannot find symbol
			resultPendingIntent = PendingIntent.getActivity(context, 0, resultIntent, PendingIntent.FLAG_MUTABLE);
			                                                                                       ^
  symbol:   variable FLAG_MUTABLE
  location: class android.app.PendingIntent

Do you know what is causing the issue and how to fix that?

![Screenshot 2022-06-17 at 12 06 20](https://user-images.githubusercontent.com/12171220/174277813-5b20fa54-11b6-463e-a9b3-f08e6a120c7d.png)
![Screenshot 2022-06-17 at 12 05 52](https://user-images.githubusercontent.com/12171220/174277819-69f231b5-2a53-465c-92eb-45ebced04f1e.png)

**Comment by gokadzev** [comment]
@mtrnik Hello, have you used "Sync project with gradle files" or capacitor sync after installing package?

**Comment by mtrnik** [comment]
@gokadzev no, should I?

**Comment by gokadzev** [comment]
> @gokadzev no, should I?

yes, are you using ionic?

**Comment by mtrnik** [comment]
@gokadzev yes I am using Ionic-Vue

I synced project with gradle files but still the same error message in console. (MainActivity.java looks visually good now)

**Comment by gokadzev** [comment]
@mtrnik try to run `ionic cap sync` in project root folder with terminal (not in android folder)

**Comment by mtrnik** [comment]
@gokadzev I did that several times before

**Comment by gokadzev** [comment]
@mtrnik i use this plugin in ionic project for test as well but there's not any error. maybe you need to clear cache with `rm -r $HOME/.gradle/caches/` from terminal and reopen project.

**Comment by patrickjquinn** [comment]
I just ran a clean -> build and this was resolved for me FYI

**Comment by sanderschnydrig** [comment]
I'm getting the same error, cleaning project didnt help, as well as @gokadzevs proposal

**Comment by gokadzev** [comment]
@mtrnik @sanderschnydrig what's your compile sdk version?

**Comment by sanderschnydrig** [comment]
I'm not getting this error anymore after invalidating caches and setting 
 ```
compileSdkVersion = 31
targetSdkVersion = 31
```
in the variables.gradle file.

@gokadzev thanks, wish I saw your comment earlier.

**Comment by sanderschnydrig** [comment]
Getting a similar error now after updating to Angular 12 which causes the Android app to crash on startup after the splash screen:

```console
 Caused by: java.lang.IllegalArgumentException: ch.pomona.newsapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.gokadzev.capacitormusiccontrols.MusicControlsNotification.createBuilder(MusicControlsNotification.java:209)
        at com.gokadzev.capacitormusiccontrols.MusicControlsNotification.updateNotification(MusicControlsNotification.java:81)
        at com.gokadzev.capacitormusiccontrols.CapacitorMusicControls.updateMetadata(CapacitorMusicControls.java:224)
        at com.gokadzev.capacitormusiccontrols.CapacitorMusicControls.create(CapacitorMusicControls.java:42)
        	... 9 more
```

**Comment by FloryanFilip** [comment]
@gokadzev what if we want to target 30?
