### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by sanderschnydrig** [gokadzev/capacitor-music-controls-plugin-new#9]
Running the app on an iPhone 5s simulator with iOS 12.4 produces the following runtime error in Xcode:

```console
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file CapacitorMusicControlsPluginNew/Plugin.swift, line 175
2022-07-11 13:29:20.835727+0200 App[75764:805906] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file CapacitorMusicControlsPluginNew/Plugin.swift, line 175
```

concerning the following Code:

```swift
if(urlPath != nil && defaultManager.fileExists(atPath: urlPath!)){
    coverImage = UIImage(contentsOfFile: urlPath!)! // <- issue is this null-safety operator on UIImage()
} else {
    coverImage = nil;
}
```

I guess iPhones of older architecture are handling null safety differently or not at all. Is there a way to handle this without the app crashing?

**Comment by sanderschnydrig** [comment]
I know nothing about Swift but some things about null safety.

Changing this line to the following resolved the crash for me:

```swift
coverImage = UIImage(contentsOfFile: urlPath!) ?? UIImage();
```

**Comment by gokadzev** [comment]
> I know nothing about Swift but some things about null safety.
> 
> Changing this line to the following resolved the crash for me:
> 
> ```swift
> coverImage = UIImage(contentsOfFile: urlPath!) ?? UIImage();
> ```

i'm not able to test plugin on ios so i will make blind push with your information.
